### ISSUE TITLE
Add scaling options

### ISSUE THREAD

**Issue by csherratt** [gfx-rs/genmesh#51]
The primitives right now just produce a primitive that is close to a unit vector. The original idea was that people would scale the primitives using the `.vertex()` trait. There are a few cases where I don't think this is satisfactory. The `cone` primitive for example has different normals based on these values, so for the sake of our uses we should add them.

**Comment by kvark** [comment]
Indeed, the addition of normals makes this point strong. We could also adjust the UVs. E.g. a cube with sizes (5, 1, 1) should have more UV space alongside X axis.
