### ISSUE TITLE
Cube SharedVertex/IndexedPolygon creates 24 vertices

### ISSUE THREAD

**Issue by Rhuagh** [gfx-rs/genmesh#52]
Shouldn't it create only 8 vertices?

**Comment by kvark** [comment]
No, because while we have 8 unique positions, the normals are different per face.
Supporting a cube generator without normals / tex-coords could be useful, but three-rs in particular doesn't need it, and it's a main client of `genmech`.

**Comment by Rhuagh** [comment]
I guess that's true, I just couldn't find a use case for individual normals per vertex per face. Didn't think of texture coordinates.

**Comment by Rhuagh** [comment]
And I thought SharedVertex was for emitting shared vertices?

**Comment by kvark** [comment]
> I just couldn't find a use case for individual normals per vertex per face

If you need normals at all, then how do you see them not being individual per face of a cube?

> And I thought SharedVertex was for emitting shared vertices?

Shared vertices != shared positions

**Comment by Rhuagh** [comment]
I come from collision/geometry, I tend to forget graphics things :) In geometry you only need the face normals or the vertex normals, you don't need to duplicate the face normal for each vertex.

Anyways, I understand now.
