### ISSUE TITLE
Use `nalgebra` instead of `cgmath`

### ISSUE THREAD

**Issue by azriel91** [gfx-rs/genmesh#65]
Heya, since most other gamedev related libraries are on `nalgebra`, I'd like to update this library to use that as well.

Another reason is that the current version on crates.io (`0.6.2`) depends on `cgmath 0.16.1`, which depends on `rand v0.4.6`. By swapping to `nalgebra`, at least for the `amethyst` game engine, we get to remove at least both the `cgmath` and `rand` crate compilations (there may be others, but I haven't done a thorough check).

I'm thinking in the future, if `ultraviolet` becomes the standard, we *could* put the relevant math library choice behind feature flags, though that's something in the future future.

**Comment by kvark** [comment]
Hi @azriel91 !

I don't think there is a single blessed math library in Rust ecosystem. Changing one by another would be good for some and bad for others. `genmesh` is specifically designed in such a way that the math doesn't show up in the API, it's basically an implementation detail.

If your goal is to make Amethyst dependency tree smaller, than I think one way to get there would be implementing a separate `nalgebra` way in `genmesh`, similarly to `cgmath` behind an optional feature. That would live alongside the `cgmath` code. Although, honestly, I'm not a big fan of supporting 2 math backends here :/

Also, `rand` is an optional [dependency](https://github.com/rustgd/cgmath/blob/50a345b7c439c492a9c658dbb432f6cbd70a0557/Cargo.toml#L27) that we aren't enabling here, so it shouldn't be dragged into the fray.

**Comment by azriel91** [comment]
Heya :wave:

> I'm not a big fan of supporting 2 math backends here :/
Yeaps agree.

> Also, `rand` is an optional [dependency](https://github.com/rustgd/cgmath/blob/50a345b7c439c492a9c658dbb432f6cbd70a0557/Cargo.toml#L27)

Ah, it's optional on `master`.
[`cgmath 0.16.1`](https://github.com/rustgd/cgmath/blob/v0.16.1/Cargo.toml#L27) always pulls `rand 0.4` (current `genmesh` release depends on this);  
[`cgmath 0.17.0`](https://github.com/rustgd/cgmath/blob/v0.17.0/Cargo.toml#L27) always pulls `rand 0.6` (current `genmesh` `master` uses this).

Anyway, I think the final decision would be best made by you<sup>1</sup>, but I'm happy to do the work to make it happen. I do imagine a future where `ultraviolet` becomes *the blessed library*, in case that factors into the decision.

Haha, sometimes we just want a `Vector3` and some math operations.

---

<sup>1</sup> As much as possible, maintenance burden should not be decided/imposed by non-maintainers.

**Comment by kvark** [comment]
Yes, you are right. We may need to make a breaking release to have the rand dependency truly optional...

A path I haven't noted, which perhaps is the true way to go, is just manually implementing the math. There shouldn't be too much logic in here, we could get away without using any math libraries.

**Comment by VictorKoenders** [comment]
I'd suggest exposing [mint](https://docs.rs/mint/0.5.5/mint/) types. The rust ecosystem seems to be heading for making mint the default math interop library, so projects that depend on this crate can use their own math library.

Both [nalgebra](https://nalgebra.org/changelog/#version-014) and [cgmath](https://github.com/rustgd/cgmath/blob/master/CHANGELOG.md#added-4) support conversions from and to mint types

**Comment by kvark** [comment]
@VictorKoenders genmesh already exposes `mint` types. This discussion is about what genmesh should use internally for computations.

**Comment by termhn** [comment]
I believe this and #66 can be closed now due to #69
